# Generated by Django 3.0.5 on 2020-04-25 05:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_drawn', models.BooleanField(default=False)),
                ('card_type', models.CharField(choices=[('action', 'action'), ('property', 'property'), ('property wild card', 'property wild card'), ('rent', 'rent'), ('money', 'money')], max_length=255)),
                ('color', models.CharField(choices=[('brown', 'brown'), ('blue', 'blue'), ('light_green', 'light_green'), ('light_blue', 'light_blue'), ('orange', 'orange'), ('pink', 'pink'), ('black', 'black'), ('red', 'red'), ('yellow', 'yellow'), ('green', 'green')], max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('secondary_color', models.CharField(choices=[('brown', 'brown'), ('blue', 'blue'), ('light_green', 'light_green'), ('light_blue', 'light_blue'), ('orange', 'orange'), ('pink', 'pink'), ('black', 'black'), ('red', 'red'), ('yellow', 'yellow'), ('green', 'green')], max_length=255)),
                ('dollar_value', models.IntegerField(null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='game.Game')),
                ('user_hand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hand_cards', to=settings.AUTH_USER_MODEL)),
                ('user_table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tables_cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'card',
            },
        ),
    ]
