# Generated by Django 3.0.5 on 2020-04-26 02:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('deck', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='victim_amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='victim_limit',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='user_table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='table_cards', to=settings.AUTH_USER_MODEL),
        ),
    ]
