# Generated by Django 3.0.5 on 2020-04-25 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turn', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dealbreaker',
            table='deal_breaker',
        ),
        migrations.AlterModelTable(
            name='payment',
            table='payment',
        ),
    ]
