# Generated by Django 3.0.5 on 2020-04-26 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('turn', '0002_auto_20200425_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='move',
            name='is_active',
            field=models.NullBooleanField(default=None),
        ),
        migrations.AlterField(
            model_name='payment',
            name='move',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turn.Move'),
        ),
        migrations.AlterUniqueTogether(
            name='move',
            unique_together={('turn', 'is_active'), ('turn', 'index')},
        ),
    ]
