# Generated by Django 3.0.5 on 2020-04-27 12:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('turn', '0003_auto_20200426_0251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='move',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='turn.Move'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='victim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
