# Generated by Django 3.0.5 on 2020-04-27 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turn', '0004_auto_20200427_1244'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
