# Generated by Django 3.0.5 on 2020-05-23 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deck', '0003_auto_20200427_2235'),
        ('turn', '0005_delete_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='forceddeal',
            name='received',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forced_deal_received', to='deck.Card'),
        ),
        migrations.AlterField(
            model_name='forceddeal',
            name='offered',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forced_deal_offered', to='deck.Card'),
        ),
        migrations.AlterField(
            model_name='forceddeal',
            name='requested',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forced_deal_requested', to='deck.Card'),
        ),
        migrations.AlterField(
            model_name='slydeal',
            name='received',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sly_deal_received', to='deck.Card'),
        ),
        migrations.AlterField(
            model_name='slydeal',
            name='requested',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sly_deal_requested', to='deck.Card'),
        ),
    ]
