# Generated by Django 3.0.5 on 2020-04-25 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='order',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
