# Generated by Django 3.0.5 on 2020-04-25 13:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0003_auto_20200425_0517'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='player',
            unique_together={('game', 'user'), ('game', 'order'), ('game', 'is_winner')},
        ),
    ]
